### PR TITLE
Add p5-Mojo-SQLite and dependencies

### PR DESCRIPTION
**Pull request by qbit**
Ports created with `portgen` and tweaked a tiny bit for `CATEGORY`

### CODE REVIEW

**Review by jcs — APPROVED** [review]

**Comment by qbit** [comment]
committed!

**Comment by dimpase** [comment]
Wait, are PRs allowed here?

**Comment by qbit** [comment]
Hi @dimpase , a few obsd devs (including myself) want to try out working with PRs.

There isn't an official "process" for doing it though. The intention is mostly to try and figure out a workflow that would .. work (obviously commits will only happen in CVS).

I'd say feel free to send PRs here, but know that the number of eyes watching are significantly fewer.

**Comment by qbit** [comment]
Yep, ultimately the diff would be committed to cvs by an openbsd dev.

I'd also like to get basic checks happening via hooks. I did some initial work on the checks here: https://github.com/qbit/improved-succotash/tree/main/.hooks

**Pull request closed without merging**
